// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZiRSbzGBP-nUhmBWrZ_SHr21rFcE-i8',
    appId: '1:559662382860:web:837d96b25377f618f8d329',
    messagingSenderId: '559662382860',
    projectId: 'recipesapp-e0faa',
    authDomain: 'recipesapp-e0faa.firebaseapp.com',
    storageBucket: 'recipesapp-e0faa.firebasestorage.app',
    measurementId: 'G-D2B3HM7D08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Q73GJjd3sNfREAruOp_FQuIxYPw2ho0',
    appId: '1:559662382860:android:e8adc0d42d8fc405f8d329',
    messagingSenderId: '559662382860',
    projectId: 'recipesapp-e0faa',
    storageBucket: 'recipesapp-e0faa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQ0VJ-2W0zJ6iy8HAerwUD7Hr7fCk8q4',
    appId: '1:559662382860:ios:d8f926bdd2aecb4ef8d329',
    messagingSenderId: '559662382860',
    projectId: 'recipesapp-e0faa',
    storageBucket: 'recipesapp-e0faa.firebasestorage.app',
    iosBundleId: 'com.example.mis2lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQ0VJ-2W0zJ6iy8HAerwUD7Hr7fCk8q4',
    appId: '1:559662382860:ios:d8f926bdd2aecb4ef8d329',
    messagingSenderId: '559662382860',
    projectId: 'recipesapp-e0faa',
    storageBucket: 'recipesapp-e0faa.firebasestorage.app',
    iosBundleId: 'com.example.mis2lab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYZiRSbzGBP-nUhmBWrZ_SHr21rFcE-i8',
    appId: '1:559662382860:web:b9f34bd6416ec518f8d329',
    messagingSenderId: '559662382860',
    projectId: 'recipesapp-e0faa',
    authDomain: 'recipesapp-e0faa.firebaseapp.com',
    storageBucket: 'recipesapp-e0faa.firebasestorage.app',
    measurementId: 'G-69X1YLRV50',
  );
}
